# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'manni-ios' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for manni-ios
  pod 'DVB', :git => 'https://github.com/manni-app/DVB.git', :branch => 'master'
  pod 'Material'
  pod 'FontAwesome.swift'
end

target 'manni-watchos Extension' do
  use_frameworks!

  pod 'DVB', :git => 'https://github.com/manni-app/DVB.git', :branch => 'master'
end